### ISSUE TITLE
Missing metadata without citations (")

### ISSUE THREAD

**Issue by dsvedberg** [icane/pyaxis#26]
First of all. thank you for creating this helpful package. 

I have a questions about the function *metadata_split_to_dict*.

Looking at the [PX-file format specification](https://www.scb.se/globalassets/vara-tjanster/px-programmen/[px-file_format_specification_2013.pdf), there are multiple keywords that are not enclosed in citations, for example integers (e.g. DECIMALS and SHOWDECIMALS) and [boolean YES/NO](https://www.scb.se/en/services/statistical-programs-for-px-files/px-file-format/keywords-with-yesno-option/). 

I might be missing something, but is there a reason that the following regex expression is used to parse the values to the metadata dictionary?
``
metadata[name] = re.findall('"[ ]*(.+?)[ ]*"+?', values)
``
The values of these key-value pairs will be lost, even though I'm sure there might be a reason for this. 

I'm looking at ways of recreating a valid PX-file from a dataframe and a metadata dictionary, and want to keep all metadata of the original file.

**Comment by lla11358** [comment]
Thank you @dsvedberg for your observation.

Reviewing the code (I haven't worked on it for years), maybe the only reason to exclude such metadata is the difficulty to write a regular expression that matches both quoted values or lists of quoted values, and non-quoted values. We just extract the metadata required for our needs...

Anyway, I'm working on it again. I think we'll find a solution in a reasonable time lapse.

**Comment by lla11358** [comment]
Hi!

Pyaxis v0.4.0 has been released (https://pypi.org/project/pyaxis/). I have taken the opportunity to upgrade the versions of Python and the Numpy and Requests packages, in order to fix some security alerts.

Thanks again for using this little tool :-)
